In [6]:
import numpy as np

# playing with 3d array sorting
d = np.array([
    [
        [29,21,24],
        [17,14,17]
    ],
    [
        [4,1,5],
        [6,9,0]
    ]
])

print(d.shape)
d.sort(axis=1)
print(d)

(2, 2, 3)
[[[17 14 17]
  [29 21 24]]

 [[ 4  1  0]
  [ 6  9  5]]]
