In [7]:
import numpy as np

# playing with 3d array sorting
d = np.array([
    [
        [29,21,24],
        [17,14,17]
    ],
    [
        [4,1,5],
        [6,9,0]
    ]
])

print(d.shape)
d.sort(axis=1)
print(d)

(2, 2, 3)
[[[17 14 17]
  [29 21 24]]

 [[ 4  1  0]
  [ 6  9  5]]]


In [13]:
# playing with 4d array sorting
e = np.array([
    [
        [
            [29,21,24],
            [17,14,17]
        ],
        [
            [29,21,24],
            [17,14,17]
        ]
    ],
    [
        [
            [4,1,5],
            [6,9,0]
        ],
        [
            [29,21,24],
            [17,14,17]
        ]
    ],
    [
        [
            [232,654,679],
            [584,904,203]
        ],
        [
            [29,21,24],
            [17,14,17]
        ]
    ],
])

print(e.shape)
e.sort(axis=3)
print(e)

(3, 2, 2, 3)
[[[[ 21  24  29]
   [ 14  17  17]]

  [[ 21  24  29]
   [ 14  17  17]]]


 [[[  1   4   5]
   [  0   6   9]]

  [[ 21  24  29]
   [ 14  17  17]]]


 [[[232 654 679]
   [203 584 904]]

  [[ 21  24  29]
   [ 14  17  17]]]]
