# 6. Manipulating Array Content

#### Task 1: Concatenate arrays

In [5]:
import numpy as np

# write code to concatenate the following arrays on axis = 0

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = np.full((3,3),1.5)

c = np.arange(0,15).reshape(5,3)

print(a.shape)
print(b.shape)
print(c.shape)

print(np.concatenate((a,b,c)))

(3, 3)
(3, 3)
(5, 3)
[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 0.   1.   2. ]
 [ 3.   4.   5. ]
 [ 6.   7.   8. ]
 [ 9.  10.  11. ]
 [12.  13.  14. ]]


In [6]:
# write code to concatenate the following arrays on axis = 1

a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[11,12,13,14]])

b = np.random.randint(100,200,(4,6))

c = np.arange(0,40).reshape(4,10)

print(a.shape)
print(b.shape)
print(c.shape)

print(np.concatenate((a,b,c), axis=1))

(4, 4)
(4, 6)
(4, 10)
[[  1   2   3   4 185 135 140 114 105 146   0   1   2   3   4   5   6   7
    8   9]
 [  4   5   6   7 170 176 100 120 100 117  10  11  12  13  14  15  16  17
   18  19]
 [  7   8   9  10 125 166 154 169 103 122  20  21  22  23  24  25  26  27
   28  29]
 [ 11  12  13  14 177 109 134 175 129 189  30  31  32  33  34  35  36  37
   38  39]]


# 8. Sorting arrays

#### Task 1: Basic sorting