In [2]:
# initialisation
import numpy as np

# 3. Create Numpy arrays

#### Task 1: Create 1-d numpy array

In [20]:
# write Python code to create 1-d Numpy arrays containing the values as follows:

# (a) [0,1,2,3,4,5,6,7]
a = np.array([0,1,2,3,4,5,6,7])
print(a)
print()

# (b) [1.2,1.4,1.6,1.8,2.0]
b = np.array([1.2,1.4,1.6,1.8,2.0], dtype = float)
print(b)
print()

# (c) ['Mary', 'John', 'Peter', 'Christine']
c = np.array(['Mary', 'John', 'Peter', 'Christine'])
print(c)
print()

# (d) ['2017-10-01', '2017-10-02', '2017-10-03',….., '2017-10-31'] 
d = np.arange('2017-10-01', '2017-10-31', dtype='datetime64')
print(d)
print()

# (e) 10 random decimal numbers between 0  and 1
e = np.random.uniform(0,1,size=10)
# e = np.random.sample(10)
print(e)
print()

# (f) 20 random whole numbers between 100 and 200
f = np.random.randint(100,200,size=20)
print(f)
print()

# (g) 50 evenly spaced numbers between 5 and 10 
g = np.linspace(5,10,50)
print(g)
print()

[0 1 2 3 4 5 6 7]

[1.2 1.4 1.6 1.8 2. ]

['Mary' 'John' 'Peter' 'Christine']

['2017-10-01' '2017-10-02' '2017-10-03' '2017-10-04' '2017-10-05'
 '2017-10-06' '2017-10-07' '2017-10-08' '2017-10-09' '2017-10-10'
 '2017-10-11' '2017-10-12' '2017-10-13' '2017-10-14' '2017-10-15'
 '2017-10-16' '2017-10-17' '2017-10-18' '2017-10-19' '2017-10-20'
 '2017-10-21' '2017-10-22' '2017-10-23' '2017-10-24' '2017-10-25'
 '2017-10-26' '2017-10-27' '2017-10-28' '2017-10-29' '2017-10-30']

[0.9856419  0.88252984 0.91659435 0.79701539 0.76456815 0.0886444
 0.6219601  0.92387675 0.53091992 0.52586655]

[143 151 192 114 110 101 131 140 144 163 180 120 171 156 183 138 130 122
 117 122]

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.653061

#### Task 2: Create 2-d numpy array

In [35]:
# Write Python code to create 2-d Numpy arrays containing the values as follows

# (a)		2x4 array [(1,2,3,4), (5,6,7,8)]
a = np.array([(1,2,3,4), (5,6,7,8)])
print(a)
print()

# (b)		3x3 array [(1.5,2.5,3.5),(4.5,5.5,6.5),(7.5,8.5,9.5)]
b = np.array([(1.5,2.5,3.5),(4.5,5.5,6.5),(7.5,8.5,9.5)])
print(b)
print()

# (c)		3x3 array [(1.6,1.7,1.8),(2.5,5.0,7.5),(20,40,60)]
c = np.array([(1.6,1.7,1.8),(2.5,5.0,7.5),(20,40,60)])
print(c)
print()

# (d)		3x4 2-d array, with initial value zero
d = np.zeros((3,4))
print(d)
print()

# (e)		5x5 2-d array with initial value one
e = np.ones((5,5))
print(e)
print()

# (f)		4x3 2-d array with initial value 10.5
f = np.full((4,3),10.5,dtype=float)
print(f)
print()

# (g)		4x4 identity matrix
g = np.eye(4)
print(g)
print()

# (h)		4x8 array with random values between 1 and 6
h = np.random.uniform(1,6,(4,8))
print(h)
print()

[[1 2 3 4]
 [5 6 7 8]]

[[1.5 2.5 3.5]
 [4.5 5.5 6.5]
 [7.5 8.5 9.5]]

[[ 1.6  1.7  1.8]
 [ 2.5  5.   7.5]
 [20.  40.  60. ]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1.35616048 5.67099361 3.28078367 4.92373435 2.10285092 4.53467201
  5.30797826 3.11128793]
 [4.15120541 1.60751517 4.17946077 1.90968888 3.96715005 3.69081469
  3.30719734 5.67846367]
 [4.64713772 1.96776158 3.8869496  5.8895509  3.54610194 5.52838278
  3.61014953 1.7275535 ]
 [1.70391875 3.27596504 3.74064923 5.18727358 5.99849387 4.50039333
  1.58003947 2.19896404]]



# 4. Inspect Numpy arrays

#### Task 1: Use the  shape, ndim, size properties and len function

In [57]:
a = np.array([1.55,1.73,1.9,1.72,1.66,1.8])
b = np.array([('red', 'green', 'yellow', 'blue'),(True,False, False, True), 
('2017-10-01', '2017-11-11', '2017-12-23', '2018-03-31')])
c = np.array([
        [
            (10,9,8,7),
            (6,5,4,3)
        ], 
        [   (1,2,3,4),
            (5,6,7,8)
        ]
]
)

# text file contains multiple datatypes, so all are indicated as string and comma as separator
d = np.loadtxt("/Users/iylia/Library/Mobile Documents/com~apple~CloudDocs/SP/Intro to Programming for DS/Lab 2/Lab2_Dataset/data1.txt",dtype="str",delimiter=",")

print("shape")
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print()
print("len")
print(len(a))
print(len(b))
print(len(c))
print(len(d))
print()
print("ndim")
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print()
print("size")
print(a.size)
print(b.size)
print(c.size)
print(d.size)

shape
(6,)
(3, 4)
(2, 2, 4)
(4, 4)

len
6
3
2
4

ndim
1
2
3
2

size
6
12
16
16


#### Task 2: Use the type function, dtype property

In [65]:
print("Array 1")
print(type(a))
print(a.dtype)
print()
print("Array 2")
print(type(b))
print(b.dtype)
print()
print("Array 3")
print(type(c))
print(c.dtype)
print()
print("Array 4")
print(type(d))
print(d.dtype)

Array 1
<class 'numpy.ndarray'>
float64

Array 2
<class 'numpy.ndarray'>
<U10

Array 3
<class 'numpy.ndarray'>
int64

Array 4
<class 'numpy.ndarray'>
<U10


# 5. Manipulating Array Shapes

#### Task 1: Flatten an array

In [71]:
# (a)	Write Python code to convert the multi-dimensional array a, into a 1-D array
a = np.array([ ['Mary', 'John','Bob'], 
               ['Zoe', 'Chris','Ann'],
               ['Leon', 'Kathy','Sam']])

print(a.ravel())

['Mary' 'John' 'Bob' 'Zoe' 'Chris' 'Ann' 'Leon' 'Kathy' 'Sam']


#### Task 2: Reshape arrays

In [77]:
# (a)	Write Python code to convert the following 1-D array a into a 3x5 multi-dimensional array
a = np.arange(15,30)

print(a.reshape((3,5)))
print()

# (b)	Convert the following 2x6 array b into a 3x4 array
b = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])

print(b.reshape((3,4)))

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Task 3: Transpose array

In [81]:
# (a)	Write Python code to transpose the following array
a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])

print(a)
print()
print(a.T)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


# 6. Manipulating Array Content

#### Task 1: Concatenate Arrays

In [82]:
# (a) write code to concatenate the following arrays on axis = 0

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = np.full((3,3),1.5)

c = np.arange(0,15).reshape(5,3)

print(a.shape)
print(b.shape)
print(c.shape)

print(np.concatenate((a,b,c)))

(3, 3)
(3, 3)
(5, 3)
[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 0.   1.   2. ]
 [ 3.   4.   5. ]
 [ 6.   7.   8. ]
 [ 9.  10.  11. ]
 [12.  13.  14. ]]


In [84]:
# (b) write code to concatenate the following arrays on axis = 1

a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[11,12,13,14]])

b = np.random.randint(100,200,(4,6))

c = np.arange(0,40).reshape(4,10)

print(a.shape)
print(b.shape)
print(c.shape)

print(np.concatenate((a,b,c), axis=1))

(4, 4)
(4, 6)
(4, 10)
[[  1   2   3   4 192 120 103 174 111 172   0   1   2   3   4   5   6   7
    8   9]
 [  4   5   6   7 139 150 194 147 154 159  10  11  12  13  14  15  16  17
   18  19]
 [  7   8   9  10 168 197 183 119 162 136  20  21  22  23  24  25  26  27
   28  29]
 [ 11  12  13  14 121 190 172 157 171 187  30  31  32  33  34  35  36  37
   38  39]]


#### Task 2: Split arrays

In [4]:
# (a)	Write Python code to split the following array into 20 sub-arrays

x = np.arange(100)

np.hsplit(x,20)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34]),
 array([35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44]),
 array([45, 46, 47, 48, 49]),
 array([50, 51, 52, 53, 54]),
 array([55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64]),
 array([65, 66, 67, 68, 69]),
 array([70, 71, 72, 73, 74]),
 array([75, 76, 77, 78, 79]),
 array([80, 81, 82, 83, 84]),
 array([85, 86, 87, 88, 89]),
 array([90, 91, 92, 93, 94]),
 array([95, 96, 97, 98, 99])]

In [6]:
# (b)	Write Python code to split the following array at these intervals: 10, 25, 45, 75, 95

x = np.arange(100)

np.hsplit(x,[10,25,45,75,95])

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44]),
 array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
        62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]),
 array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
        92, 93, 94]),
 array([95, 96, 97, 98, 99])]

# 7. Copying arrays

#### Task 1: Make a copy of a Numpy array

In [5]:
# (a)	What is the difference between y and z?

x = np.array([1, 2, 3])

y = x

z = np.copy(x)

print(f'y = {y}')
print(f'z = {z}')
print()
print(f'There is no difference between y and z')

y = [1 2 3]
z = [1 2 3]

There is no difference between y and z


In [9]:
# (b)	What is the value of x, y and z after executing Line 4?

x = np.array([1, 2, 3])

y = x

z = np.copy(x)

x[0] = 10

print(f'x = {x}')
print()
print(f'After executing "x[0] = 10",\nx = {x}\ny = {y}\nz = {z}')
print()
print(f'z becomes the original x before changing the first value in the array')

x = [10  2  3]

After executing "x[0] = 10",
x = [10  2  3]
y = [10  2  3]
z = [1 2 3]

z becomes the original x before changing the first value in the array


# 8. Sorting arrays

#### Task 1: Basic sorting

In [10]:
# (a) write code to sort the following 1d-array in-place using the sort method

arr_1 = np.random.randint(100,200,10)

print('**Before sorting**')
print(arr_1)

arr_1.sort()
print('\n**After sorting**')
print(arr_1)

**Before sorting**
[125 170 193 135 161 191 127 135 149 189]

**After sorting**
[125 127 135 135 149 161 170 189 191 193]


In [11]:
# (b) write code to sort the following 2-d array in-place by columns

arr_2 = np.random.randint(1,20,(3,5))

print('**Before sorting**')
print(arr_2)

arr_2.sort(axis=0)
print('\n**After sorting**')
print(arr_2)

**Before sorting**
[[ 9 15  5 18  7]
 [19 13  2 14  9]
 [ 2  2  5  9 12]]

**After sorting**
[[ 2  2  2  9  7]
 [ 9 13  5 14  9]
 [19 15  5 18 12]]


In [12]:
# (c) write code to sort the following 2d-array by rows without affecting the original

arr_3 = np.random.randint(100,200,(2,5))

print('**Before sorting - original array**')
print(arr_3)

arr_3c = np.copy(arr_3)
arr_3c.sort(axis=1)

print('\n**After calling sort method - original array**')
print(arr_3)

print('\nAfter calling sort method - copy of sorted array**')
print(arr_3c)

**Before sorting - original array**
[[110 105 191 118 183]
 [149 187 191 186 119]]

**After calling sort method - original array**
[[110 105 191 118 183]
 [149 187 191 186 119]]

After calling sort method - copy of sorted array**
[[105 110 118 183 191]
 [119 149 186 187 191]]


# 9. Subsetting and Indexing

#### Task 1: Basic subsetting

In [14]:
a = np.arange(1,100,1)
b = np.array([[1,2,3,4],[100,200,300,400],[5,6,7,8],[9,10,11,12]])

In [19]:
# (a)	What is the output of a[3] and b[3]? What is the datatype of each output?

print(f'"a[3]" = {a[3]}')
print(f'"a[3]" datatype = {a[3].dtype}')
print()
print(f'"b[3]" = {b[3]}')
print(f'"b[3]" datatype = {b[3].dtype}')

"a[3]" = 4
"a[3]" datatype = int64

"b[3]" = [ 9 10 11 12]
"b[3]" datatype = int64


In [21]:
# (b)	Write Python code to print out 2nd and third rows of the array b (ie [100,200,300,400] and [5,6,7,8]

print(f'The 2nd and 3rd rows of array b are {b[1:3]}')

The 2nd and 3rd rows of array b are [[100 200 300 400]
 [  5   6   7   8]]


In [25]:
# (c)	Write Python code to print out all the rows of the last column of array b

print(f'All the rows of the last column of array b are {b[:5,3]}')

All the rows of the last column of array b are [  4 400   8  12]


In [26]:
# (d)	Write Python code to print out row 2 (i.e.[ 100,200,300,400], first  and last columns of array b

print(f'First column of row 2 of array b is {b[1][0]}\nLast column of row 2 of array b is {b[1][3]}')

First column of row 2 of array b is 100
Last column of row 2 of array b is 400


In [27]:
# (e)	Write Python code to print out row 3 to end, column 2 to end of the array b

print(f'Row 3 to end and column 2 to end of array b is {b[2:,1:]}')

Row 3 to end and column 2 to end of array b is [[ 6  7  8]
 [10 11 12]]


In [32]:
# (f)	Write Python code to print out elements from index 10 to 20 with step 2 from array a

print(a[10:21:2])

[11 13 15 17 19 21]


In [34]:
# (g)	Write Python code to select and reverse elements in array a from index 0 to the end, then print it out.

print(a[::-1])

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]


#### Task 2: Boolean indexing

In [35]:
a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))

b = np.random.randint(100,200,(3,3))

In [36]:
# (a) write code to return all even numbers in array a

print(a)
print()

# a_even = a % 2 == 0
# a = a[a_even]
# print(a)

print(a[a%2==0])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [37]:
# (b) write code to return all the numbers that are greater than 150 in array b

print(b)
print()

# b_over_150 = b > 150
# b = b[b_over_150]
# print(b)

print(b[b>150])

[[143 149 167]
 [129 153 138]
 [130 101 198]]

[167 153 198]


#### Task 3: Indexing using WHERE

In [85]:
# Given the following Numpy array,  print out the values and the rows and indexes where the element is greater than 5.

b = np.arange(9.).reshape(3, 3)
# Hint: A new Numpy array b5 containing the indices of wherever 5 occurs is created
# You can iterate through b5 to identify the exact row and column of each index
b5 = np.where( b > 5 )
# b5i = list(map(list, zip(*b5))) # convert tuple of row and column indices arrays into two lists then zip into list of paired indices and save as one list

print(f'*** Values of where the elements are, and their rows/columns ***')
for r,c in list(map(list, zip(*b5))):
    print(f'Value: {b[r][c]:.0f} in row {r}, column {c}')

*** Values of where the elements are, and their rows/columns ***
Value: 6 in row 2, column 0
Value: 7 in row 2, column 1
Value: 8 in row 2, column 2


# 10. Array Math

#### Task 1: Add, subtract, multiply and divide numpy arrays

In [3]:
# initialising arrays for part 10

a = np.arange(100,200,1).reshape(20,5) 
b = np.arange(1,2000,20).reshape(10,10) 
c = np.array([[1,2,3],[4,5,6]])

In [6]:
# (a)	What happens when you try to perform the following operations on array a and array b?

np.add(a,b)
# print(a+b)

# the array cannot be printed as their shapes are different

ValueError: operands could not be broadcast together with shapes (20,5) (10,10) 

In [9]:
# (b)	Create an array a2 that has the same shape as array a, containing random numbers between 0 and 100. Print the contents of the resulting array when a and a2 are added together.

a2 = np.random.randint(0,100,size = (20,5))

print(np.add(a,a2))

[[104 192 149 105 121]
 [131 149 195 184 193]
 [156 165 204 168 211]
 [166 129 183 135 177]
 [148 192 167 152 219]
 [133 153 203 156 152]
 [207 203 149 190 159]
 [192 187 159 197 221]
 [178 226 197 211 148]
 [177 196 174 205 187]
 [213 166 199 225 179]
 [235 177 217 224 212]
 [202 168 165 219 195]
 [249 260 177 217 187]
 [243 259 206 184 198]
 [273 250 234 234 272]
 [212 217 259 244 206]
 [186 190 214 263 285]
 [285 197 240 281 209]
 [274 274 240 240 262]]


In [22]:
# (c)	Extract a subset of array b into an array variable b1, such that you can perform a subtraction operation of (b1 – c) successfully.  Print out the resulting contents of the array of this operation.

# shape of c is (2.3)
# shape of b is (10,10)

b1 = np.random.choice(b
                        .flatten(), 
                        size = (2,3)) # subset of b in same shape of c

print(np
        .subtract(b1,c))

[[1420  839 1218]
 [ 797  496  615]]


In [31]:
# (d)	Extract a subset of array a into an array variable a2, 

# •	where a2 contains numbers that are even
# •	a2 is the same shape as array c

a2 = np.random.choice(a[a%2==0] # subset a where a2 contanins even numbers
                        .flatten(), # flatten subset as np.random.choice only takes 1-D arrays
                        size = (2,3)) # change shape to be same as array c

In [33]:
# (e)	Create an array c2 such that c2 contains the values of array c multiplied by 10.

# Using the array a2 created in part (d), perform a division operation of (a2 / c2) and print out the resulting contents of the array of this operation.

c2 = np.multiply(c,10)

print(np.divide(a2,c2))

[[19.2         8.4         4.        ]
 [ 3.          3.76        2.46666667]]


# 11. Statistical Methods

#### Task 1: sum, mean (SUBMISSION REQUIRED)

In [34]:
a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))

print("Contents of array a")
print(a)
print()

# (a)	What is the sum of all the numbers in array a?
print("*** Sum of all numbers in a ***")
print(a.sum())
print()

# (b)	What is their mean?
print("*** Mean of all numbers in a ***")
print(a.mean())
print()

# (c)	What is the sum of all the numbers in each row?
print("*** Sum of all numbers in each row ***")
print(f"Row 1 sum = {a.sum(axis=1)[0]}")
print(f"Row 2 sum = {a.sum(axis=1)[1]}")
print(f"Row 3 sum = {a.sum(axis=1)[2]}")
print(f"Row 4 sum = {a.sum(axis=1)[3]}")

Contents of array a
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

*** Sum of all numbers in a ***
780

*** Mean of all numbers in a ***
19.5

*** Sum of all numbers in each row ***
Row 1 sum = 45
Row 2 sum = 145
Row 3 sum = 245
Row 4 sum = 345


#### Task 2: std, var

In [46]:
a = np.arange(10, 50, 0.5)
b = np.arange(10, 20, 0.1)

print(f'Contents of array a\n{a}')
print()
print(f'Contents of array b\n{b}')
print()

# (a)	What is the standard deviation of arrays a and b?

print('*** Standard deviation ***')
print(f'SD of a = {np.std(a):.10f}')
print(f'SD of b = {np.std(b):.11f}')
print()

# (b)	What is the variance of arrays a and b?
print('*** Variance ***')
print(f'VAR of a = {(np.std(a))**2:.4f}')
print(f'VAR of b = {(np.std(b))**2:.4f}')

Contents of array a
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5]

Contents of array b
[10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9]

*** Standard deviation ***
SD of a = 11.54

#### Task 3: min/max, argmin/argmax

In [129]:
a = np.random.randint(1,1000,(3,4))

# Print out the following information:
# •	maximum value of each row in array a
# •	maximum value of the entire array a
# •	row and column that has the number with the maximum value in array a
# •	minimum value of each column in array a
# •	minimum value of the entire array a
# •	row and column that has the number with the minimum value in array a

print('***Contents of array a***')
print(a)
print()
# for idx, row in enumerate(a):
#     print(f'Max a at row {idx} is {a[idx].max()}')
for row, idx in enumerate(a.argmax(axis=1)): # enumerating argmax outputs the row index and the index of the value in that row
    print(f'Max a at row {row} is {a[row,idx]}')
print()
print(f'Max a = {a.max()}')
print(f'Row and Column of {a.max()} is ([{list(map(list, zip(*np.where(a == a.max()))))[0][0]}],[{list(map(list, zip(*np.where(a == a.max()))))[0][1]}])')
print()
for row, idx in enumerate(a.argmin(axis=1)):
    print(f'Min a at row {row} is {a[row,idx]}')
print()
print(f'Min a = {a.min()}')
print(f'Row and Column of {a.min()} is ([{list(map(list, zip(*np.where(a == a.min()))))[0][0]}],[{list(map(list, zip(*np.where(a == a.min()))))[0][1]}])')


***Contents of array a***
[[ 79 543  22 792]
 [308 383 908 366]
 [445 216 661 911]]

Max a at row 0 is 792
Max a at row 1 is 908
Max a at row 2 is 911

Max a = 911
Row and Column of 911 is ([2],[3])

Min a at row 0 is 22
Min a at row 1 is 308
Min a at row 2 is 216

Min a = 22
Row and Column of 22 is ([0],[2])


#### Task 4: cumsum, cumprod