# 6. Manipulating Array Content

#### Task 1: Concatenate arrays

In [5]:
import numpy as np

# (a) write code to concatenate the following arrays on axis = 0

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = np.full((3,3),1.5)

c = np.arange(0,15).reshape(5,3)

print(a.shape)
print(b.shape)
print(c.shape)

print(np.concatenate((a,b,c)))

(3, 3)
(3, 3)
(5, 3)
[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 0.   1.   2. ]
 [ 3.   4.   5. ]
 [ 6.   7.   8. ]
 [ 9.  10.  11. ]
 [12.  13.  14. ]]


In [6]:
# (b) write code to concatenate the following arrays on axis = 1

a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10],[11,12,13,14]])

b = np.random.randint(100,200,(4,6))

c = np.arange(0,40).reshape(4,10)

print(a.shape)
print(b.shape)
print(c.shape)

print(np.concatenate((a,b,c), axis=1))

(4, 4)
(4, 6)
(4, 10)
[[  1   2   3   4 185 135 140 114 105 146   0   1   2   3   4   5   6   7
    8   9]
 [  4   5   6   7 170 176 100 120 100 117  10  11  12  13  14  15  16  17
   18  19]
 [  7   8   9  10 125 166 154 169 103 122  20  21  22  23  24  25  26  27
   28  29]
 [ 11  12  13  14 177 109 134 175 129 189  30  31  32  33  34  35  36  37
   38  39]]


# 8. Sorting arrays

#### Task 1: Basic sorting

In [10]:
import random

# (a) write code to sort the following 1d-array in-place using the sort method

arr_1 = np.random.randint(100,200,10)

print('**Before sorting**')
print(arr_1)

arr_1.sort()
print('\n**After sorting**')
print(arr_1)

**Before sorting**
[146 162 167 149 120 109 110 168 168 163]

**After sorting**
[109 110 120 146 149 162 163 167 168 168]


In [15]:
# (b) write code to sort the following 2-d array in-place by columns

arr_2 = np.random.randint(1,20,(3,5))

print('**Before sorting**')
print(arr_2)

arr_2.sort(axis=0)
print('\n**After sorting**')
print(arr_2)

**Before sorting**
[[ 8  8 17  4  4]
 [11 13 11 16  2]
 [ 7 16 12  9 14]]

**After sorting**
[[ 7  8 11  4  2]
 [ 8 13 12  9  4]
 [11 16 17 16 14]]


In [17]:
# (c) write code to sort the following 2d-array by rows without affecting the original

arr_3 = np.random.randint(100,200,(2,5))

print('**Before sorting - original array**')
print(arr_3)

arr_3c = np.copy(arr_3)
arr_3c.sort(axis=1)

print('\n**After calling sort method - original array**')
print(arr_3)

print('\nAfter calling sort method - copy of sorted array**')
print(arr_3c)

**Before sorting - original array**
[[134 144 140 155 153]
 [168 126 164 138 114]]

**After calling sort method - original array**
[[134 144 140 155 153]
 [168 126 164 138 114]]

After calling sort method - copy of sorted array**
[[134 140 144 153 155]
 [114 126 138 164 168]]


# 9. Subsetting and Indexing

#### Task 2: Boolean indexing

In [18]:
a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))

b = np.random.randint(100,200,(3,3))

In [21]:
# (a) write code to return all even numbers in array a

print(a)

# a_even = a % 2 == 0
# a = a[a_even]
# print(a)

print(a[a%2==0])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [25]:
# (b) write code to return all the numbers that are greater than 150 in array b

print(b)

# b_over_150 = b > 150
# b = b[b_over_150]
# print(b)

print(b[b>150])

[[167 156 143]
 [114 144 177]
 [161 162 121]]
[167 156 177 161 162]


# 11. Statistical methods

#### Task 1: sum, mean

# 12. File I/O on Numpy arrays

#### Task 1: Load and save a numpy array 

In [20]:
import numpy as np

### Read the csv file with the loadtxt() function
fname = "/Users/iylia/Library/Mobile Documents/com~apple~CloudDocs/SP/Intro to Programming for DS/Lab 2/Lab2_Dataset/singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv"
data = np.loadtxt(fname,skiprows=1,dtype=[('year','i8'),('level_1','U50'),('value','i8')],delimiter=",")

### Print out total rows of data in the file
print(f"There are altogether {len(data)} rows of data in the file {fname}")
print()

### Print out the number of years of data captured
data_years = data['year']  # Just extract the year column
years = np.unique(data_years)   # Get the unique values in this column
print(f"There are {len(years)} years of data captured from 1960 to 2016")
print()

### Extract only the rows with “Total Residents" in the “level_1” column
keyword = 'Total Residents'
column_to_search = data['level_1']
out = [i for i, v in enumerate(column_to_search) if keyword in v]
data_totalresidents = data[out]

### Print out the year which has the highest total number of residents
max = data_totalresidents['value'].max()
argmax = data_totalresidents['value'].argmax()
print(f"Year with the highest total number of residents: {str(data_totalresidents[argmax]['year'])}")
print(f"Population Count: {str(max)}")
print()

### Print out the year which has the lowest total number of residents
min = data_totalresidents['value'].min()
argmin = data_totalresidents['value'].argmin()

print(f"Year with the highest total number of residents: {str(data_totalresidents[argmin]['year'])}")
print(f"Population Count: {str(min)}")
print()


There are altogether 855 rows of data in the file /Users/iylia/Library/Mobile Documents/com~apple~CloudDocs/SP/Intro to Programming for DS/Lab 2/Lab2_Dataset/singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv

There are 57 years of data captured from 1960 to 2016

Year with the highest total number of residents: 2016
Population Count: 3933559

Year with the highest total number of residents: 1960
Population Count: 1646400

