# 3. Create Numpy arrays

#### Task 1: Create 1-d numpy array

In [20]:
import numpy as np

# write Python code to create 1-d Numpy arrays containing the values as follows:

# (a) [0,1,2,3,4,5,6,7]
a = np.array([0,1,2,3,4,5,6,7])
print(a)
print()

# (b) [1.2,1.4,1.6,1.8,2.0]
b = np.array([1.2,1.4,1.6,1.8,2.0], dtype = float)
print(b)
print()

# (c) ['Mary', 'John', 'Peter', 'Christine']
c = np.array(['Mary', 'John', 'Peter', 'Christine'])
print(c)
print()

# (d) ['2017-10-01', '2017-10-02', '2017-10-03',….., '2017-10-31'] 
d = np.arange('2017-10-01', '2017-10-31', dtype='datetime64')
print(d)
print()

# (e) 10 random decimal numbers between 0  and 1
e = np.random.uniform(0,1,size=10)
# e = np.random.sample(10)
print(e)
print()

# (f) 20 random whole numbers between 100 and 200
f = np.random.randint(100,200,size=20)
print(f)
print()

# (g) 50 evenly spaced numbers between 5 and 10 
g = np.linspace(5,10,50)
print(g)
print()

[0 1 2 3 4 5 6 7]

[1.2 1.4 1.6 1.8 2. ]

['Mary' 'John' 'Peter' 'Christine']

['2017-10-01' '2017-10-02' '2017-10-03' '2017-10-04' '2017-10-05'
 '2017-10-06' '2017-10-07' '2017-10-08' '2017-10-09' '2017-10-10'
 '2017-10-11' '2017-10-12' '2017-10-13' '2017-10-14' '2017-10-15'
 '2017-10-16' '2017-10-17' '2017-10-18' '2017-10-19' '2017-10-20'
 '2017-10-21' '2017-10-22' '2017-10-23' '2017-10-24' '2017-10-25'
 '2017-10-26' '2017-10-27' '2017-10-28' '2017-10-29' '2017-10-30']

[0.9856419  0.88252984 0.91659435 0.79701539 0.76456815 0.0886444
 0.6219601  0.92387675 0.53091992 0.52586655]

[143 151 192 114 110 101 131 140 144 163 180 120 171 156 183 138 130 122
 117 122]

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.653061

#### Task 2: Create 2-d numpy array

In [35]:
# Write Python code to create 2-d Numpy arrays containing the values as follows

# (a)		2x4 array [(1,2,3,4), (5,6,7,8)]
a = np.array([(1,2,3,4), (5,6,7,8)])
print(a)
print()

# (b)		3x3 array [(1.5,2.5,3.5),(4.5,5.5,6.5),(7.5,8.5,9.5)]
b = np.array([(1.5,2.5,3.5),(4.5,5.5,6.5),(7.5,8.5,9.5)])
print(b)
print()

# (c)		3x3 array [(1.6,1.7,1.8),(2.5,5.0,7.5),(20,40,60)]
c = np.array([(1.6,1.7,1.8),(2.5,5.0,7.5),(20,40,60)])
print(c)
print()

# (d)		3x4 2-d array, with initial value zero
d = np.zeros((3,4))
print(d)
print()

# (e)		5x5 2-d array with initial value one
e = np.ones((5,5))
print(e)
print()

# (f)		4x3 2-d array with initial value 10.5
f = np.full((4,3),10.5,dtype=float)
print(f)
print()

# (g)		4x4 identity matrix
g = np.eye(4)
print(g)
print()

# (h)		4x8 array with random values between 1 and 6
h = np.random.uniform(1,6,(4,8))
print(h)
print()

[[1 2 3 4]
 [5 6 7 8]]

[[1.5 2.5 3.5]
 [4.5 5.5 6.5]
 [7.5 8.5 9.5]]

[[ 1.6  1.7  1.8]
 [ 2.5  5.   7.5]
 [20.  40.  60. ]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1.35616048 5.67099361 3.28078367 4.92373435 2.10285092 4.53467201
  5.30797826 3.11128793]
 [4.15120541 1.60751517 4.17946077 1.90968888 3.96715005 3.69081469
  3.30719734 5.67846367]
 [4.64713772 1.96776158 3.8869496  5.8895509  3.54610194 5.52838278
  3.61014953 1.7275535 ]
 [1.70391875 3.27596504 3.74064923 5.18727358 5.99849387 4.50039333
  1.58003947 2.19896404]]



# 4. Inspect Numpy arrays

#### Task 1: Use the  shape, ndim, size properties and len function